### ISSUE TITLE
TypeError: object supporting the buffer API required

### ISSUE THREAD

**Issue by mviallon** [bbc2/shuffled#1]
Dude,

Got an error instantiating Shuffled with seed parameter.
Python 3.5.2, cryptography 1.5.3

```
Traceback (most recent call last):
  File "test3.py", line 3, in <module>
    plop = Shuffled(10, 42)
  File "/usr/lib/python3.5/site-packages/shuffled/core.py", line 31, in __init__
    material = hashlib.sha512(self.seed).digest()
TypeError: object supporting the buffer API required
```

**Comment by bbc2** [comment]
The seed parameter is expected to be of type `bytes`.  See http://shuffled.readthedocs.io/en/latest/#shuffled.Shuffled for more information. I'll try to make that clearer. Thanks for the feedback.
