### ISSUE TITLE
Is there a way to speed up the process

### ISSUE THREAD

**Issue by MajorAdam** [bbc2/shuffled#12]
It takes nearly 4 seconds to calculate new indices of  65536 numbers

**Comment by bbc2** [comment]
I should have improved performance quite a bit in https://github.com/bbc2/shuffled/pull/15. This was included in the 1.1.0 release of the package. Does that help?

**Comment by bbc2** [comment]
Marking this as closed. Let me know if the problem wasn't fixed.
